@startuml
'https://plantuml.com/class-diagram

class ConcreteFactory
abstract AbstractProduct
interface AbstractFactory
class ConcreteProduct

AbstractProduct <|-- ConcreteProduct
AbstractFactory <|.. ConcreteFactory
ConcreteFactory <|.. ConcreteProduct

@enduml