@startuml
'https://plantuml.com/class-diagram

abstract class AbstractProduct
class ConcreteProductA
class ConcreteProductB
class SimpleFactory

AbstractProduct <|-- ConcreteProductA
AbstractProduct <|-- ConcreteProductB

SimpleFactory ..|> ConcreteProductA
SimpleFactory ..|> ConcreteProductB

@enduml